# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 373)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start_recording = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_recording.setGeometry(QtCore.QRect(20, 60, 131, 23))
        self.pushButton_start_recording.setObjectName("pushButton_start_recording")
        self.lineEdit_file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_file_name.setGeometry(QtCore.QRect(280, 23, 113, 20))
        self.lineEdit_file_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_file_name.setObjectName("lineEdit_file_name")
        self.pushButton_set_parameters = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_parameters.setGeometry(QtCore.QRect(500, 50, 111, 23))
        self.pushButton_set_parameters.setObjectName("pushButton_set_parameters")
        self.pushButton_choose_file_to_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choose_file_to_load.setGeometry(QtCore.QRect(20, 120, 131, 23))
        self.pushButton_choose_file_to_load.setObjectName("pushButton_choose_file_to_load")
        self.LogField = QtWidgets.QTextBrowser(self.centralwidget)
        self.LogField.setGeometry(QtCore.QRect(10, 200, 511, 100))
        self.LogField.setMaximumSize(QtCore.QSize(16777215, 100))
        self.LogField.setObjectName("LogField")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(500, 20, 111, 23))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.label_file_to_load = QtWidgets.QLabel(self.centralwidget)
        self.label_file_to_load.setGeometry(QtCore.QRect(150, 120, 111, 23))
        self.label_file_to_load.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_file_to_load.setObjectName("label_file_to_load")
        self.pushButton_plot_from_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot_from_file.setGeometry(QtCore.QRect(20, 150, 131, 23))
        self.pushButton_plot_from_file.setObjectName("pushButton_plot_from_file")
        self.pushButton_choose_folder_to_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choose_folder_to_save.setGeometry(QtCore.QRect(20, 20, 131, 23))
        self.pushButton_choose_folder_to_save.setObjectName("pushButton_choose_folder_to_save")
        self.label_folder_to_save = QtWidgets.QLabel(self.centralwidget)
        self.label_folder_to_save.setGeometry(QtCore.QRect(130, 20, 111, 23))
        self.label_folder_to_save.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_folder_to_save.setObjectName("label_folder_to_save")
        self.pushButton_plot_single_spectrum = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot_single_spectrum.setGeometry(QtCore.QRect(180, 60, 131, 23))
        self.pushButton_plot_single_spectrum.setObjectName("pushButton_plot_single_spectrum")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_save_parameters = QtWidgets.QAction(MainWindow)
        self.action_save_parameters.setObjectName("action_save_parameters")
        self.action_load_parameters = QtWidgets.QAction(MainWindow)
        self.action_load_parameters.setObjectName("action_load_parameters")
        self.menuTools.addAction(self.action_save_parameters)
        self.menuTools.addAction(self.action_load_parameters)
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_start_recording.setText(_translate("MainWindow", "Start recording"))
        self.lineEdit_file_name.setText(_translate("MainWindow", "File name"))
        self.pushButton_set_parameters.setText(_translate("MainWindow", "Set parameters"))
        self.pushButton_choose_file_to_load.setText(_translate("MainWindow", "Choose file to load"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect interrogator"))
        self.label_file_to_load.setText(_translate("MainWindow", "none"))
        self.pushButton_plot_from_file.setText(_translate("MainWindow", "Plot"))
        self.pushButton_choose_folder_to_save.setText(_translate("MainWindow", "Choose folder to save"))
        self.label_folder_to_save.setText(_translate("MainWindow", "none"))
        self.pushButton_plot_single_spectrum.setText(_translate("MainWindow", "Plot single spectrum"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.action_save_parameters.setText(_translate("MainWindow", "Save parameters"))
        self.action_save_parameters.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_load_parameters.setText(_translate("MainWindow", "Load parameters"))
        self.action_load_parameters.setShortcut(_translate("MainWindow", "Ctrl+L"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
